### ISSUE TITLE
Google Drive Weights

### ISSUE THREAD

**Issue by ConnorMcShane** [Capino512/pytorch-rotation-decoupled-detector#4]
Is there any chance you could make the DOTA 1.0 restnet101 weights available through google cloud or some other file sharing system? I am unable to download them as I cannot register with the Baidu download tool as they do not allow this from outside China. This would be much appreciated and thank you for your great work.

**Comment by Capino512** [comment]
I will share the weights via Google Drive as soon as possible. If you only need pre-training weights, you can find the Google Drive sharing link under this [issue](https://github.com/Capino512/pytorch-rotation-decoupled-detector/issues/1#issuecomment-799924401).

**Comment by ConnorMcShane** [comment]
Perfect, thank you so much!
