### ISSUE TITLE
nms未剔除

### ISSUE THREAD

**Issue by Lvqin001** [Capino512/pytorch-rotation-decoupled-detector#5]
你好，我在测试单张图像时，使用了rbbox_batched_nms。但是发现nms以后并未进行融合。确认Compile已完成，同时nms是没有提示相关模块缺失的错误。画出图像确认未进行nms。keeps = rbbox_batched_nms(bboxes, scores, labels, self.nms_thresh)。请问可能是什么原因？？

**Comment by Capino512** [comment]
你nms_thresh设置的多大呢，设为0.1看下有效果没

**Comment by Lvqin001** [comment]
> 你nms_thresh设置的多大呢，设为0.1看下有效果没

解决了，因为提示了the provided PTX was compiled with an unsupported toolchain. 是因为我使用的docker中的cuda版本的问题，导致了nms gpu未生效，换了一个docker环境，可以运行。谢谢你的回复

**Comment by Capino512** [comment]
哦哦，这样啊，不客气。
